version: "3.8"
services:
  db:
    image: postgres:15
    container_name: sales-db
    restart: always
    environment:
      - POSTGRES_DB=sales-db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=123456
    ports: 
      - 5432:5432
    networks:
      - nenetwork

  api:
      build:
        context: .
        dockerfile: Dockerfile
      container_name: sales-api
      environment:
        SPRING_DATASOURCE_URL: jdbc:postgresql://sales-db:5432/sales-db
        SPRING_DATASOURCE_USERNAME: admin
        SPRING_DATASOURCE_PASSWORD: 123456
        PORT: 8081
        SPRING_RABBITMQ_HOST: rabbitmq
        SPRING_RABBITMQ_PORT: 5672
        SPRING_RABBITMQ_USERNAME: guest
        SPRING_RABBITMQ_PASSWORD: guest
      ports: 
        - 8081:8081
      networks:
        - nenetwork
      depends_on:
        - rabbitmq
        - db
  
  rabbitmq:
      image: rabbitmq:3-management
      container_name: sales-rabbitmq
      restart: always
      ports: 
        - 5672:5672
        - 15672:15672
        - 25676:25676
      networks:
        - nenetwork

networks:
  nenetwork: