# Server configuration
server:
  port: ${PORT:8081}
  servlet:
    context-path: /sales-api

# Spring application name
spring:
  application:
    name: sales

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/sales-db
    username: admin
    password: 123456
    initialization-mode: always
    initialize: true
    continue-on-error: true
    platform: postgresql
    max-active: 3

  jpa:
    hibernate:
      ddl-auto: none
      format-sql: true
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    enabled: true
    locations: classpath:db/migration  # Default location for migration scripts

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
